server:
 port:
    8083
spring:
 application:
  name: ConfigServer-Service
 cloud:
  config:
   server:
    git:
     uri: https://github.com/MilindPatil95/spring-app-config
     clone-on-start: true
 

 