server:
 port: 8082




spring:
 application:
  name: Order-Service
 config:
  import: configserver:http://localhost:8083


#eureka:
#   instance:
#    hostname: localhost  
#   client:
#    register-with-eureka: true
#    fetch-registry: true   